/**
 * Concatenates supabase/migrations/*.sql (filename order) into supabase/setup.sql,
 * the single file you paste into the Supabase SQL editor on a fresh project.
 *
 *   node supabase/build-setup.mjs
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = new URL("./migrations/", import.meta.url);
const files = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();

const header = `-- LAWFIC — complete database setup.
-- Generated by supabase/build-setup.mjs from supabase/migrations/*.sql.
-- Do not edit this file; edit a migration and regenerate.
--
-- RUN THIS ONCE, ON A FRESH PROJECT. It is not re-runnable: every table, type,
-- trigger, policy and function is created without guards, so a second run
-- fails with "already exists".
--
-- To start over on a project with no data you care about:
--     drop schema public cascade;
--     create schema public;
--     grant usage on schema public to anon, authenticated, service_role;
-- then paste this file again. That destroys every table in \`public\` — never
-- run it against a database holding real wallet balances.
`;

const body = files
  .map((f) => {
    const sql = readFileSync(new URL(f, dir), "utf8");
    return `
-- ===================================================================
-- ${f}
-- ===================================================================

${sql.trim()}
`;
  })
  .join("\n");

writeFileSync(new URL("./setup.sql", import.meta.url), `${header}${body}\n`, "utf8");
console.log(`setup.sql written from ${files.length} migrations:`);
for (const f of files) console.log(`  ${f}`);
