/**
 * GENERATED by scripts/extract-banner-colours.mjs — do not edit by hand.
 *
 * The colour each banner photograph lends to the two navigation bars while it
 * is the slide on screen. Only the hue comes from the picture; the lightness
 * and saturation are pinned so the bars stay readable behind light type.
 *
 * A null means the photograph is effectively greyscale and has no hue worth
 * borrowing — those slides leave the bars on the site's own navy.
 *
 * Re-run the script after adding or replacing a photograph.
 */

export type BannerColour = { bar: string; lift: string; accent: string; wash: string };

export const bannerColours: Record<string, BannerColour | null> = {
  "/banners/branding.jpg": { bar: "#153742", lift: "#215363", accent: "#73C3DE", wash: "#DBEBF0" }, // hue 195deg, 21% of pixels carry colour
  "/banners/education.jpg": { bar: "#422F15", lift: "#634821", accent: "#DEB173", wash: "#F0E7DB" }, // hue 35deg, 13% of pixels carry colour
  "/banners/food.jpg": { bar: "#422815", lift: "#633D21", accent: "#DE9F73", wash: "#F0E4DB" }, // hue 25deg, 39% of pixels carry colour
  "/banners/gst.jpg": { bar: "#152842", lift: "#213D63", accent: "#739FDE", wash: "#DBE4F0" }, // hue 215deg, 21% of pixels carry colour
  "/banners/identity.jpg": { bar: "#422815", lift: "#633D21", accent: "#DE9F73", wash: "#F0E4DB" }, // hue 25deg, 59% of pixels carry colour
  "/banners/jobs.jpg": { bar: "#422815", lift: "#633D21", accent: "#DE9F73", wash: "#F0E4DB" }, // hue 25deg, 62% of pixels carry colour
  "/banners/legal.jpg": { bar: "#422815", lift: "#633D21", accent: "#DE9F73", wash: "#F0E4DB" }, // hue 25deg, 41% of pixels carry colour
  "/banners/membership.jpg": { bar: "#422F15", lift: "#634821", accent: "#DEB173", wash: "#F0E7DB" }, // hue 35deg, 20% of pixels carry colour
  "/banners/msme.jpg": { bar: "#423715", lift: "#635321", accent: "#DEC373", wash: "#F0EBDB" }, // hue 45deg, 10% of pixels carry colour
};
